### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by mourinhan8** [mourinhan8/Simulator_Piano#1]
Kirill Gagarski, please request me what is the best way to play sound in my application.

**Comment by gagarski** [comment]
Пока то, что выложено не запускается:
```
Exception in thread "AWT-EventQueue-0" java.lang.IllegalArgumentException: input == null!
	at javax.imageio.ImageIO.read(ImageIO.java:1388)
	at com.code.KeyBoard.<init>(KeyBoard.java:22)
	at com.code.Pianos$1.run(Pianos.java:10)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

Исходя из кода, что хотелось бы:
1. Хотелось бы иметь что-то похожее на клавиатуру пианино, на чём можно играть мышкой (а не картинку с клавиатурой)
2. Хотелось бы иметь поддержку переключения октав.
3. В связи с 2, рекомендую задумать о смене проигрывания WAV-файлов на синтезацию MIDI внутри программы:
https://docs.oracle.com/javase/tutorial/sound/MIDI-synth.html
https://docs.oracle.com/javase/7/docs/api/javax/sound/midi/Synthesizer.html

На экзамен 28-го числа можете приходить, но ваша текущая реализация по сложности пока не дотягивает до курсового проекта.

**Comment by mourinhan8** [comment]
Я исползовал синтезацию MIDI внутри прогрммы с Вашей помощью. На программе уже можно играть мышкой. Я и добавил переключение октав.
